In [12]:
import numpy as np

keep_prob=0.5
a3=np.random.rand(3,5)
print('a3:',a3)
print('a3.mean={}'.format(a3.mean()))

d3=np.random.rand(a3.shape[0],a3.shape[1])<keep_prob
print('d3:',d3)

# element-wise 相乘
a3=np.multiply(a3,d3)
print('a3:',a3)
print('a3.mean={}'.format(a3.mean()))

# 保证均值接近
a3/=keep_prob
print('a3:',a3)
print('a3.mean={}'.format(a3.mean()))



a3: [[0.26461815 0.66534146 0.29760959 0.62329532 0.77054667]
 [0.2219037  0.2472303  0.1907186  0.25500933 0.96392282]
 [0.49301162 0.28529915 0.68640562 0.02620304 0.61304923]]
a3.mean=0.44027763945282267
d3: [[ True False False False False]
 [ True  True  True  True  True]
 [ True False  True False False]]
a3: [[0.26461815 0.         0.         0.         0.        ]
 [0.2219037  0.2472303  0.1907186  0.25500933 0.96392282]
 [0.49301162 0.         0.68640562 0.         0.        ]]
a3.mean=0.22152134265219087
a3: [[0.5292363  0.         0.         0.         0.        ]
 [0.4438074  0.49446059 0.38143719 0.51001866 1.92784564]
 [0.98602325 0.         1.37281125 0.         0.        ]]
a3.mean=0.44304268530438173


In [11]:
pwd

'/Users/pengju/python-workspace/algorithm_playground/深度学习'